### ISSUE TITLE
New developer's guide 

### ISSUE THREAD

**Issue by PotatoPalooza** [NeRF-or-Nothing/web-app#20]
Documentation is needed to aid new developers working on this web app for the first time. Ideally, this would be a page in the wiki with as many sub-pages as needed. Some ideas for this page are:

- Resources for Vue.js
- Current functionality / Road Map for new features
- File structure and where everything is located
- Making your first commit guide
- Naming conventions or any other standard you think would be useful to carryon

**Comment by Jiawei-Zhao-728** [comment]
I did a good first draft of that in the wiki page
